"""add_medication_schedules_table

Revision ID: 8b29f7c1d3a4
Revises: e6cb9cf45ec3
Create Date: 2026-06-09 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, ARRAY

# revision identifiers, used by Alembic.
revision = '8b29f7c1d3a4'
down_revision = 'e6cb9cf45ec3'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_schedules',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', UUID(as_uuid=True), nullable=False),
    sa.Column('medication_id', UUID(as_uuid=True), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', 'as_needed', name='frequencytype'), nullable=False),
    sa.Column('days_of_week', ARRAY(sa.String()), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_created_at'), 'medication_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_medication_schedules_is_active'), 'medication_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_medication_schedules_medication_id'), 'medication_schedules', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_schedules_user_id'), 'medication_schedules', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_schedules_user_id'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_medication_id'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_is_active'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_created_at'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    # ### end Alembic commands ###
